server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka注册中心的微服务名称
  cloud:
    config:
      server:
        git:
          uri: git@github.com:GuanLei0213/springcloud-config.git #GitHub上面的git仓库的SSH地址
          search-paths: #搜索的目录
            - springcloud-config
      label: master #读取的分支

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进EurekaServer,默认为true
    fetch-registry: true #是否从EurekaServer中抓取自己的注册信息，默认为true,单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #服务中心的地址

