server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: false #false表示不向服务中心注册自己
    fetch-registry: false #表示自己端就是服务中心，我的职责就是维护服务实例，并不需要从EurekaServer中抓取自己的注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #集群版，相互注册，相互守望