server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #注册进服务注册中心
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080 #配置sentinel dashboard地址，和sentinel发生关系，也就是让sentinel监控该服务
        #默认8719端口，假设被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
        port: 8719
      datasource: #持久化进Nacos
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

#消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider

#激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
