server:
  port: 8006

spring:
  application:
    name: cloud-payment-service
  cloud:
    consul: #将服务注册进Consul中
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url:  jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: guanlei

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gl.springcloud.entity

