server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  cloud:
    zookeeper:
      connect-string: 10.50.7.9:2181 #注册进zookeeper
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url:  jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: guanlei

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gl.springcloud.entity

